### ISSUE TITLE
LUB del powerset di N è N

### ISSUE THREAD

**Issue by mzanella** [mzanella/vds1718#20]
**Description**
Nel 7 manca la dimostraziole che li LUB dell'insieme delle parti di N è N?

**Comment by BottCode** [comment]
Non credo, se vedi _powerset(N)_ come un reticolo completo (e lo è) è immediato rendersi conto che  il LUB è proprio N (oltre che il greatest element). 

Per rendersi conto della verità di ciò basta vedere che gli elementi appena "sotto" N non sono paragonabili fra loro e il loro LUB è la loro unione, ovvero N.

In fin dei conti, a pensarci, in un qualsiasi _powerset_ il suo LUB è il suo TOP, che nel nostro caso è l'unione di tutti i sottoinsieme di N.

Morale: credo si possa affermare senza dimostrarlo che l'unione dei subset di un powerset è il least upper bound
